name: Flag Addition
description: Sugguest a new flag
title: "[Flag]: "
labels: ["enhancement"]
assignees:
  - Kolpixx
body:
  - type: input
    id: name
    attributes:
      label: Name of the flag
    validations:
      required: true
  - type: textarea
    id: colors
    attributes:
      label: Flag Colors
      placeholder: |
        1. #FF218C
        2. #FFD800
        3. #21B...
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      placeholder: |
        Optionally add further context or an image of the flag here